# Generated by Django 5.2.4 on 2025-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GreenMed Store', max_length=100, verbose_name='Site Name')),
                ('tagline', models.CharField(default='Premium Natural Medical Products', max_length=200, verbose_name='Tagline')),
                ('email', models.EmailField(default='info@greenmedstore.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+33 1 23 45 67 89', max_length=20, verbose_name='Phone')),
                ('address', models.TextField(default='Paris, France', verbose_name='Address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('business_hours', models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', verbose_name='Business Hours')),
                ('about_text', models.TextField(default='We specialize in premium natural medical products derived from organic sources.', verbose_name='About Text')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Privacy Policy')),
                ('terms_of_service', models.TextField(blank=True, verbose_name='Terms of Service')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
