# Generated by Django 5.2.4 on 2025-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_da',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_de',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_es',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_fi',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_fr',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ga',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_hu',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_it',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_no',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_sv',
            field=models.TextField(default='We specialize in premium natural medical products derived from organic sources.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_da',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_de',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_es',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_fi',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_fr',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ga',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_hu',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_it',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_no',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_sv',
            field=models.TextField(default='Paris, France', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_da',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_de',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_en',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_es',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_fi',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_fr',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_ga',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_hu',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_it',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_no',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_sv',
            field=models.TextField(default='Mon-Fri: 9:00-18:00\nSat: 10:00-16:00\nSun: Closed', null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_da',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_de',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_en',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_es',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_ga',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_hu',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_it',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_no',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_da',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_de',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_es',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_fi',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_fr',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ga',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_hu',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_it',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_no',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_sv',
            field=models.CharField(default='GreenMed Store', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_da',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_de',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_es',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_fi',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_fr',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ga',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_hu',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_it',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_no',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_sv',
            field=models.CharField(default='Premium Natural Medical Products', max_length=200, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_da',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_de',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_en',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_es',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_ga',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_hu',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_it',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_no',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of Service'),
        ),
    ]
