# Generated by Django 5.2.4 on 2025-07-28 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="weight",
            field=models.PositiveIntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(10)]
            ),
            preserve_default=False,
        ),
    ]
