# Generated by Django 5.2.4 on 2025-07-28 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderitem_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(10)],
            ),
        ),
    ]
