# Generated by Django 5.2.4 on 2025-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_da',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_hu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_da',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_de',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_es',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_fi',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_fr',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ga',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_hu',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_it',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_no',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_sv',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_da',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_de',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_es',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_fi',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_ga',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_hu',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_it',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_no',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_sv',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_da',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fi',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ga',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hu',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_no',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_da',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_de',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_en',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_es',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_fi',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_fr',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_ga',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_hu',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_it',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_no',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_sv',
            field=models.TextField(help_text='Health benefits', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_da',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_de',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_en',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_es',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_fi',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_fr',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_ga',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_hu',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_it',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_no',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_sv',
            field=models.TextField(help_text='Key elements or ingredients', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_da',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_de',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_en',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_es',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_fi',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_fr',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_ga',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_hu',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_it',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_no',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method_sv',
            field=models.TextField(help_text='How it is produced or formulated', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_da',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fi',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ga',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hu',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_no',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sv',
            field=models.TextField(help_text='Rich text description of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_da',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_de',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_es',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_fi',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_fr',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ga',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_hu',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_it',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_no',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_sv',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_da',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_de',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_es',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_fi',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_ga',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_hu',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_it',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_no',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_sv',
            field=models.CharField(blank=True, help_text='SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_da',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_de',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_en',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_es',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_fi',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_fr',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_ga',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_hu',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_it',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_no',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_sv',
            field=models.TextField(help_text='How to use this product', null=True),
        ),
    ]
