# Generated by Django 5.2.4 on 2025-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_description_da_category_description_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="dosage_advice",
            field=models.TextField(
                blank=True, help_text="General dosage recommendations for this category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="effects_timeline",
            field=models.TextField(
                blank=True, help_text="Onset and duration information for this category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fas fa-cannabis",
                help_text="Font Awesome icon class for this category",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_medical",
            field=models.BooleanField(
                default=False, help_text="Check if this is a medical-focused category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_recreational",
            field=models.BooleanField(
                default=True,
                help_text="Check if this is a recreational-focused category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="primary_benefits",
            field=models.TextField(
                blank=True,
                help_text="Key therapeutic benefits (shown in medical info section)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="storage_advice",
            field=models.TextField(
                blank=True, help_text="Proper storage recommendations"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="strain_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sativa", "Sativa"),
                    ("Indica", "Indica"),
                    ("Hybrid", "Hybrid"),
                    ("Other", "Other"),
                ],
                help_text="Primary strain type for this category",
                max_length=10,
                null=True,
            ),
        ),
    ]
