# Generated by Django 5.2.4 on 2025-07-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_dosage_advice_category_effects_timeline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="preferred_ratio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_cbd", "High CBD (20:1)"),
                    ("balanced", "Balanced (1:1)"),
                    ("high_thc", "High THC (1:20)"),
                ],
                help_text="Suggested cannabinoid ratio for products in this category",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="recommended_methods",
            field=models.JSONField(
                blank=True,
                help_text="Suggested consumption methods (e.g., ['flower', 'oil'])",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="dosage_advice",
            field=models.TextField(
                blank=True, help_text="Recommended dosing guidance for category"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="effects_timeline",
            field=models.TextField(
                blank=True, help_text="Expected onset and duration of effects"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fas fa-cannabis",
                help_text="Font Awesome icon class",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_medical",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_recreational",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_da",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_de",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_es",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_fi",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_fr",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_ga",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_hu",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_it",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_no",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_sv",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_da",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_fi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_ga",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_hu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_it",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_keywords_sv",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="primary_benefits",
            field=models.TextField(
                blank=True,
                help_text="Key therapeutic benefits shown in medical section",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="storage_advice",
            field=models.TextField(blank=True, help_text="Proper storage instructions"),
        ),
        migrations.AlterField(
            model_name="category",
            name="strain_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sativa", "Sativa"),
                    ("Indica", "Indica"),
                    ("Hybrid", "Hybrid"),
                    ("Other", "Other"),
                ],
                help_text="Dominant strain type for this category",
                max_length=10,
                null=True,
            ),
        ),
    ]
