# Generated by Django 5.2.4 on 2025-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0005_product_preferred_ratio_product_recommended_methods_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_average",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Average rating from 0 to 5",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of ratings"),
        ),
    ]
