# Generated by Django 5.2.4 on 2025-07-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_rating_average_product_rating_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rating_average",
        ),
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Automatically calculated average rating (0-5)",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of ratings received"
            ),
        ),
    ]
