# Generated by Django 5.2.4 on 2025-07-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0007_remove_product_rating_average_product_average_rating_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="meta_description",
            field=models.CharField(blank=True, help_text="SEO meta description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_da",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_de",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_en",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_es",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_fi",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_fr",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_ga",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_hu",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_it",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_no",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_sv",
            field=models.CharField(
                blank=True, help_text="SEO meta description", null=True
            ),
        ),
    ]
